### ISSUE TITLE
[TOOL-151] Fill fact table with PR size

### ISSUE THREAD

**Issue by davidabram** [crocoder-dev/mr-tool-monorepo#300]
~~Should be triggered by MR diffs event (done)~~

Hunk parsing + is codegen (source control code) → move it to transform step

MR Size → integer → minutes - MR Diffs (Hunk)

Should calculate size per one MR!

<sub>From [SyncLinear.com](https://synclinear.com) | [TOOL-151](https://linear.app/crocoder/issue/TOOL-151/fill-fact-table-with-pr-size)</sub>

**Comment by ivke995** [comment]
MR Size → integer → minutes - MR Diffs (Hunk)  --> Should this "minutes" be "lines" or?
